TEXTS = {
    "welcome": "Welcome to Odds Bot!\nClick below to get started:",
    "choose_sport": "⚽️ Choose Sport",
    "accepted_bets": "💰 Accepted Bets",
    "pending_bets": "⏳ Pending Bets",
    "back": "Back",
    "cancel": "Cancel",
    "accepted_bets_title": "\U0001F4B0 Accepted Bets:\n\n",
    "no_accepted_bets": "No accepted bets.",
    "pending_bets_title": "\u23F3 Pending Bets:\n\n",
    "no_pending_bets": "No pending bets.",
    "cancel_pending": "Cancel: {desc}...",
    "choose_event": "Choose an event:",
    "choose_outcome": "Choose an outcome (Bookmaker: {bookmaker}):",
    "chosen_outcome": "You have chosen: {outcome} at odds {odds}\n\nEnter your bet amount in EUR (e.g. 200):",
    "invalid_amount": "Please enter a valid positive number for your bet amount in EUR, or type /start to go back.",
    "bet_placed": "Bet placed and pending!\nOutcome: {outcome}\nOdds: {odds}\nAmount: {amount} EUR\n{win_str}",
    "potential_win": "Potential win: {potential_win:.2f} EUR",
    "error_sports": "Sorry, could not load sports right now.",
    "error_events": "Sorry, could not load events for this sport.",
    "error_odds": "Sorry, could not load odds for this event.",
    "clicked": "You clicked: {data}",
    "confirm_cancel_pending": "Are you sure you want to cancel this pending bet?",
    "yes-cancel": "Yes, I want to cancel this bet",
    "no": "No",
    "confirm_bet": "Please confirm your bet:\n{event}\nOutcome: {outcome}\nOdds: {odds}\nAmount: {amount} EUR",
    "confirm_bet_button": "Confirm Bet",
    "edit_bet_button": "Edit",
    "bet_confirmed": "Your bet has been placed and is now pending!",
    "bet_history": "📊 Bet History",
    "bet_history_title": "\U0001F4CA Bet History:\n\n",
    "bet_history_no_bets": "No past bets yet.",
    "bet_history_headers": "Event | Outcome | Odds | Amount | Result | P/L",
    "bet_win": "✅ Win",
    "bet_loss": "❌ Loss",
    "bet_push": "➖ Push",
    "bet_profit": "💰 +{amount} EUR",
    "bet_loss_amt": "🔻 -{amount} EUR",
    "bet_history_prev": "⬅️ Previous Page",
    "bet_history_next": "Next Page ➡️",
    "bet_history_back": "Back to History",
    "bet_detail_date": "Date: {date}",
    "bet_detail_event": "Event: {event}",
    "bet_detail_outcome": "Outcome: {outcome}",
    "bet_detail_odds": "Odds: {odds}",
    "bet_detail_amount": "Amount: {amount} EUR",
    "bet_detail_result": "Result: {result}  {pl}",
} 