TEXTS = {
    "welcome": "Welcome to Odds Bot!\nClick below to get started:",
    "choose_sport": "Choose Sport",
    "accepted_bets": "Accepted Bets",
    "pending_bets": "Pending Bets",
    "back": "Back",
    "cancel": "Cancel",
    "accepted_bets_title": "\U0001F4B0 Accepted Bets:\n\n",
    "no_accepted_bets": "No accepted bets.",
    "pending_bets_title": "\u23F3 Pending Bets:\n\n",
    "no_pending_bets": "No pending bets.",
    "cancel_pending": "Cancel: {desc}...",
    "choose_event": "Choose an event:",
    "choose_outcome": "Choose an outcome (Bookmaker: {bookmaker}):",
    "chosen_outcome": "You have chosen: {outcome} at odds {odds}\n\nEnter your bet amount in EUR (e.g. 200):",
    "invalid_amount": "Please enter a valid positive number for your bet amount in EUR, or type /back to go back.",
    "bet_placed": "Bet placed and pending!\nOutcome: {outcome}\nOdds: {odds}\nAmount: {amount} EUR\n{win_str}",
    "potential_win": "Potential win: {potential_win:.2f} EUR",
    "error_sports": "Sorry, could not load sports right now.",
    "error_events": "Sorry, could not load events for this sport.",
    "error_odds": "Sorry, could not load odds for this event.",
    "clicked": "You clicked: {data}",
    "confirm_cancel_pending": "Are you sure you want to cancel this pending bet?",
    "yes-cancel": "Yes, I want to cancel this bet",
    "no": "No",
} 